const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');

const DIGESTS_DIR = path.join(__dirname, '../../output/digests');

// Email config from environment
const EMAIL_CONFIG = {
  host: process.env.EMAIL_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.EMAIL_PORT || '587', 10),
  user: process.env.EMAIL_USER || '',
  pass: process.env.EMAIL_PASS || '',
  to: process.env.EMAIL_TO || ''
};

function getLatestDigest() {
  if (!fs.existsSync(DIGESTS_DIR)) {
    return null;
  }

  const files = fs.readdirSync(DIGESTS_DIR)
    .filter(f => f.endsWith('.md'))
    .sort()
    .reverse();

  if (files.length === 0) return null;
  return path.join(DIGESTS_DIR, files[0]);
}

function markdownToHtml(markdown) {
  // Simple markdown to HTML conversion
  let html = markdown
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="color: #6B46C1; border-bottom: 1px solid #E2E8F0; padding-bottom: 8px;">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="color: #2D3748;">$1</h1>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" style="color: #6B46C1;">$1</a>')
    // List items
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Paragraphs (lines not already wrapped)
    .replace(/^(?!<[hlu]|<li)(.+)$/gm, '<p style="margin: 8px 0;">$1</p>')
    // Clean up empty paragraphs
    .replace(/<p style="margin: 8px 0;"><\/p>/g, '')
    // Wrap consecutive li elements in ul
    .replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul style="padding-left: 20px;">${match}</ul>`);

  // Wrap in styled container
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 700px; margin: 0 auto; padding: 20px; background: #F7FAFC; color: #2D3748;">
  <div style="background: white; padding: 30px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
    ${html}
  </div>
  <p style="text-align: center; color: #A0AEC0; font-size: 12px; margin-top: 20px;">
    Generated by Scout Agent
  </p>
</body>
</html>`;
}

async function sendEmail(digestPath) {
  const markdown = fs.readFileSync(digestPath, 'utf8');
  const html = markdownToHtml(markdown);
  const date = path.basename(digestPath, '.md');

  const transporter = nodemailer.createTransport({
    host: EMAIL_CONFIG.host,
    port: EMAIL_CONFIG.port,
    secure: EMAIL_CONFIG.port === 465,
    auth: {
      user: EMAIL_CONFIG.user,
      pass: EMAIL_CONFIG.pass
    }
  });

  const mailOptions = {
    from: `"Scout Agent" <${EMAIL_CONFIG.user}>`,
    to: EMAIL_CONFIG.to,
    subject: `Scout Report - ${date}`,
    text: markdown,
    html: html
  };

  const info = await transporter.sendMail(mailOptions);
  return info;
}

async function main() {
  console.log(`\nScout Delivery - ${new Date().toISOString()}\n`);

  // Validate config
  if (!EMAIL_CONFIG.user || !EMAIL_CONFIG.pass || !EMAIL_CONFIG.to) {
    console.error('Error: Email configuration missing.');
    console.error('Required environment variables:');
    console.error('  EMAIL_USER - SMTP username/email');
    console.error('  EMAIL_PASS - SMTP password or app password');
    console.error('  EMAIL_TO   - Recipient email address');
    process.exit(1);
  }

  // Find latest digest
  const digestPath = getLatestDigest();
  if (!digestPath) {
    console.error('No digest found. Run npm run digest first.');
    process.exit(1);
  }

  console.log(`Digest: ${path.basename(digestPath)}`);
  console.log(`To: ${EMAIL_CONFIG.to}`);
  console.log(`Via: ${EMAIL_CONFIG.host}:${EMAIL_CONFIG.port}`);

  try {
    const info = await sendEmail(digestPath);
    console.log(`\nEmail sent successfully!`);
    console.log(`Message ID: ${info.messageId}`);
  } catch (error) {
    console.error(`\nFailed to send email: ${error.message}`);
    if (error.code === 'EAUTH') {
      console.error('Authentication failed. Check EMAIL_USER and EMAIL_PASS.');
      console.error('For Gmail, use an App Password: https://myaccount.google.com/apppasswords');
    }
    process.exit(1);
  }
}

main();
